apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj-deployment
  namespace: my-net
  labels:
    app: project1-dep
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: my-container
        image: shudhodhan/testrepo:REPLACE_TAG
        ports:
        - containerPort: 80
