apiVersion: v1
kind: Service
metadata:
  name: proj-service
  namespace: my-net
  labels:
    app: project1-svc
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
